#!/usr/bin/env python3
"""Stage the pre-relocated Zynaps program image for the on-target build.

The reconstructed cores address the game as ``image + <Ghidra address>``, so every byte of the
original .PRG's text has to be present in the shim's BSS image at exactly those offsets — not
because the cores execute any of it, but because they READ it: the filename table at 0x19686, the
tune streams the sound driver walks, the per-section tables, the boot palette at 0x19618, the
sprite sources. GEMDOS relocates a .PRG for whatever address it loads it at, which is not ours, so
the relocation is done HERE, by the same loader the differential harness uses
(``tools/recreate_kit/oracle/loader.py``), and ``zynaps_main.c`` reads the result straight into the
image with one GEMDOS Fread.

EXTENT: ``[load_base, load_base + tlen)`` — the TEXT ONLY, and that is the difference from Joust's
copy of this file. Zynaps has no data segment and a 0x54a28-byte BSS, so the program's full span
runs to 0x6e96e; emitting all of it would put 346 KB of guaranteed zeros on the emulated drive and
read them back over an array TOS has already zeroed. The cores that read above 0x19f46 are reading
the game's own BSS, which is zero at boot on both shores — the harness's loader leaves it zeroed
too (``loader.load_image``: "BSS is left zeroed"), so the two agree by construction rather than by
this file copying zeros around. What the shim MUST NOT do is skip the zeroing: the image is a .bss
array, and TOS zeroes .bss.

The result is a build artifact derived from ``../../bin/ZYNAPS17.PRG`` (itself untracked); it is
regenerated by build.sh and gitignored.

Usage: gen_image.py <ZYNAPS17.PRG> <disk/ZYNAPS.IMG>
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3] / "tools"))       # reverse/tools — the shared recreate kit
from recreate_kit import project                         # noqa: E402
project.load(HERE.parent)                                # recreate/ — binds the kit's loader
import loader                                            # noqa: E402
import prg_dis                                           # noqa: E402


def main():
    prg, out = sys.argv[1], sys.argv[2]
    image = loader.load_image(prg)                       # also sets loader.PROGRAM_END
    header = prg_dis.parse_header(Path(prg).read_bytes())
    lo = loader.LOAD_BASE
    # tlen + dlen rather than tlen alone: the loader copies both verbatim and a game with a data
    # segment would otherwise be staged short. Zynaps' dlen is 0, so this is the general spelling
    # of "everything the file actually carries", not a claim about this binary.
    hi = lo + header["tlen"] + header["dlen"]
    blob = bytes(image[lo:hi])
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_bytes(blob)
    print(f"{out}: {len(blob)} bytes  [{lo:#x},{hi:#x})  "
          f"bss {header['blen']:#x} left to TOS, program ends {loader.PROGRAM_END:#x}")


if __name__ == "__main__":
    main()
