#!/usr/bin/env python3
"""Emit tables.c / tables.h — the trigonometry and reciprocals the raycaster may not compute.

The target has no libm and no time for one: every transcendental the frame needs is a build-time
table here, in the same fixed-point format spike.h declares. Two tables and nothing else, because a
table that is never indexed is dead weight in a 1 MB machine:

  spike_sin[BRAD_FULL]        sin(angle) in 16.16, angle in BRAD_FULL units per turn. Cosine is the
                              same table read a quarter turn along, so there is no second table.
  spike_recip[RECIP_ENTRIES]  |1/v| in 16.16 for v a 16.16 magnitude, indexed by v >> RECIP_SHIFT.
                              This is the DDA's deltaDist: one lookup replaces a 32-bit divide per
                              ray per axis, and 320 of those a frame is the difference between a
                              raycast stage that fits the budget and one that does not.

WHY A COARSE INDEX IS NOT A COARSE PICTURE. Quantising v to RECIP_SHIFT bits makes the reciprocal
of a SMALL v very wrong in relative terms — and that is exactly the ray whose sideDist along that
axis is enormous, so the DDA never steps that way and the error never reaches the frame. The axis
that decides the hit has a large v, where the same quantisation is a fraction of a percent. Entry 0
and everything under RECIP_MAX's reciprocal clamp to RECIP_MAX, which is longer than the map's
diagonal, so a ray exactly along an axis simply never steps across the other one.

tan is NOT tabulated: the only tangent in the whole program is tan(FOV/2), a single build-time
constant (spike.h's TAN_HALF_FOV_8_8), and this script CHECKS that spike.h's value is the one this
FOV really wants rather than restating it.

Usage: gen_tables.py <spike.h> <tables.h> <tables.c>
"""
import math
import re
import sys

HEADER_GUARD = "SPIKE_TABLES_H"
VALUES_PER_LINE = 8


def spike_constants(path):
    """The #define'd integer constants of spike.h, so this script and the C agree by construction."""
    text = open(path).read()
    plain = re.findall(r"^#define\s+(\w+)\s+(-?(?:0x)?[0-9a-fA-F]+)L?\s*(?:/\*.*)?$", text, re.M)
    consts = {name: int(value, 0) for name, value in plain}
    # RECIP_ENTRIES and friends are written in terms of the ones above; evaluate them the same way
    # the preprocessor would rather than hard-coding a second copy of the arithmetic here.
    derived = re.findall(r"^#define\s+(\w+)\s+(\(.*?\))\s*(?:/\*.*)?$", text, re.M)
    for _ in range(len(derived)):
        for name, expr in derived:
            if name in consts:
                continue
            try:
                consts[name] = int(eval(expr.replace("L", "").replace("(int)", ""), {}, consts))
            except (NameError, TypeError, SyntaxError):
                pass
    return consts


def emit_array(out, ctype, name, values):
    out.append(f"const {ctype} {name}[] = {{")
    for start in range(0, len(values), VALUES_PER_LINE):
        row = values[start:start + VALUES_PER_LINE]
        out.append("    " + ", ".join(str(v) for v in row) + ",")
    out.append("};")
    out.append("")


def main():
    spike_h, out_h, out_c = sys.argv[1], sys.argv[2], sys.argv[3]
    k = spike_constants(spike_h)
    brad, fix_one = k["BRAD_FULL"], k["FIX_ONE"]
    entries, shift, recip_max = k["RECIP_ENTRIES"], k["RECIP_SHIFT"], k["RECIP_MAX"]

    want_tan = round(math.tan(math.radians(k["FOV_DEGREES"] / 2)) * 256)
    if want_tan != k["TAN_HALF_FOV_8_8"]:
        raise SystemExit(f"REFUSED: spike.h says TAN_HALF_FOV_8_8 = {k['TAN_HALF_FOV_8_8']}, but a "
                         f"{k['FOV_DEGREES']} degree field of view wants {want_tan}")

    sine = [int(round(math.sin(2 * math.pi * a / brad) * fix_one)) for a in range(brad)]
    # A 16.16 sine must not reach +65536 at the quarter turn: the raycaster multiplies it by a 8.8
    # camera offset and the product has to stay inside a signed long.
    sine = [max(-fix_one + 1, min(fix_one - 1, v)) for v in sine]

    recip = [recip_max if i == 0 else min(recip_max, (fix_one * fix_one) // (i << shift))
             for i in range(entries)]

    header = [
        "/* tables.h — GENERATED by gen_tables.py. Do not edit; edit the generator. */",
        f"#ifndef {HEADER_GUARD}",
        f"#define {HEADER_GUARD}",
        "",
        "/* sin(angle) in 16.16, angle in BRAD_FULL units per turn. cos is spike_sin a quarter along. */",
        "extern const long spike_sin[];",
        "/* |1/v| in 16.16 for a 16.16 magnitude v, indexed by v >> RECIP_SHIFT, clamped to RECIP_MAX. */",
        "extern const long spike_recip[];",
        "",
        f"#endif /* {HEADER_GUARD} */",
        "",
    ]
    body = ['/* tables.c — GENERATED by gen_tables.py. Do not edit; edit the generator. */', '']
    emit_array(body, "long", "spike_sin", sine)
    emit_array(body, "long", "spike_recip", recip)

    open(out_h, "w").write("\n".join(header))
    open(out_c, "w").write("\n".join(body))
    print(f"{out_c}: sin={len(sine)} recip={len(recip)} tan_half_fov_8_8={want_tan}")


if __name__ == "__main__":
    main()
