/* tables.h — GENERATED by gen_tables.py. Do not edit; edit the generator. */
#ifndef SPIKE_TABLES_H
#define SPIKE_TABLES_H

/* sin(angle) in 16.16, angle in BRAD_FULL units per turn. cos is spike_sin a quarter along. */
extern const long spike_sin[];
/* |1/v| in 16.16 for a 16.16 magnitude v, indexed by v >> RECIP_SHIFT, clamped to RECIP_MAX. */
extern const long spike_recip[];

#endif /* SPIKE_TABLES_H */
