#!/usr/bin/env python3
"""gen_hud_fixture.py — bake the remaster HUD's inputs into the on-target demo.

remaster only renders the HUD so far, and the HUD reads a set of assets (font, colour-fill table,
mask/cursor tables, the gauge string, and the dashboard graphic from buf_c) plus a HudState — all of
which normally come from the recreate loaders. Rather than run those on-target, we capture them once
on the host (same adapter the equivalence tests use), stage a realistic mid-race background, and emit:

  build/hud_fixture.h  — C arrays (background + assets + palette) and the HudState values main.c uses
  build/golden.bin     — recreate's g_draw_hud output on the SAME background/state (the byte-for-byte
                         reference: remaster's on-target frame must equal this)
  build/palette.bin    — the 16 ST palette words, for the PNG the headless run writes

Because remaster's HUD is already pixel-identical to recreate on the host, a byte-match of the
on-target dump against golden.bin proves the remaster C is correct compiled+run on a real 68000.
"""
import ctypes
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REMASTER = HERE.parents[1]                       # remaster/
sys.path.insert(0, str(REMASTER / "test"))

import adapter                                    # noqa: E402  flat-image -> struct extraction
import equiv                                      # noqa: E402  mid-race staging + recreate pipeline

RACE_PALETTE = 0x17fa2                            # in-race palette (A_race_palette; loaded before the
                                                  # leg starts, reloaded by sprite-mode 4) — 16 ST words
PALETTE_BYTES = 32
# A visually busy mid-race HUD: a few flag bars + fuel columns, a plausible speed/time.
CONTROLS = {adapter.A_flag_seq_count: 3, adapter.A_crash_lap: 4,
            adapter.A_speed: 120, adapter.A_time_left: 45}


def _c_array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + "".join(f"0x{b:02x}," for b in data[i:i + 16]))
    lines.append("};")
    return "\n".join(lines)


def main():
    build = HERE / "build"
    build.mkdir(exist_ok=True)

    img = equiv.hud_background(leg=0, controls=CONTROLS)
    sb, nb = adapter.SCREEN_BASE, adapter.SCREEN_BYTES
    background = bytes(img[sb:sb + nb])

    # recreate's HUD frame on the same staged image = the golden reference.
    ref = bytearray(img)
    equiv._run_pipeline(ref, ("g_draw_hud",))
    (build / "golden.bin").write_bytes(bytes(ref[sb:sb + nb]))

    palette = bytes(img[RACE_PALETTE:RACE_PALETTE + PALETTE_BYTES])
    (build / "palette.bin").write_bytes(palette)

    st = adapter.hud_state(img)
    buf_c = int.from_bytes(img[adapter.A_buf_c:adapter.A_buf_c + 4], "big")

    def win(addr, n):
        return bytes(img[addr:addr + n])

    arrays = {
        "fixture_background":     background,
        "fixture_font":           win(adapter.A_font_glyphs, adapter.FONT_BYTES),
        "fixture_color_pairs":    win(adapter.A_color_pairs, adapter.COLOR_PAIRS_BYTES),
        "fixture_color_bar_mask": win(adapter.A_color_bar_mask, adapter.COLOR_BAR_MASK_BYTES),
        "fixture_color_bar_cidx": win(adapter.A_color_bar_cidx - adapter.CIDX_ZERO_OFF,
                                      adapter.CIDX_WINDOW_BYTES),
        "fixture_fuel_mask":      win(adapter.A_fuel_mask, adapter.FUEL_MASK_BYTES),
        "fixture_gauge_str":      win(adapter.A_gauge_str, adapter.GAUGE_STR_BYTES),
        "fixture_palette":        palette,
    }

    out = ["/* Generated by gen_hud_fixture.py — do not edit. Captured HUD inputs for the on-target",
           " * demo: the mid-race background, the static asset tables, the dashboard graphic, the",
           " * palette, and the HudState scalars. */",
           "#ifndef RM_HUD_FIXTURE_H", "#define RM_HUD_FIXTURE_H", "#include <stdint.h>", ""]
    for name, data in arrays.items():
        out.append(_c_array(name, data))
    out.append(_c_array("fixture_dashboard_src", win(buf_c + adapter.DASH_SRC_OFF, adapter.DASH_SRC_BYTES)))
    out += ["",
            f"#define CIDX_ZERO_OFF        {adapter.CIDX_ZERO_OFF}",
            f"#define HUD_FLAG_SEQ_COUNT   {st.flag_seq_count}",
            f"#define HUD_FLAG_SEQ_OFF     {st.flag_seq_off}",
            f"#define HUD_DSP_COLOR_SCROLL {st.dsp_color_scroll}",
            f"#define HUD_CRASH_LAP        {st.crash_lap}",
            f"#define HUD_SPEED            {st.speed}",
            f"#define HUD_TIME_LEFT        {st.time_left}",
            f"#define HUD_GAME_OVER        {st.game_over}",
            "", "#endif /* RM_HUD_FIXTURE_H */", ""]
    (build / "hud_fixture.h").write_text("\n".join(out))
    print(f"wrote {build/'hud_fixture.h'}, golden.bin, palette.bin "
          f"(flag={st.flag_seq_count} lap={st.crash_lap} speed={st.speed} time={st.time_left})")


if __name__ == "__main__":
    main()
