#!/usr/bin/env python3
"""gen_sound_fixture.py — bake the REFRESH sound driver's program-data constants into
render/atari/build/sound_data.h (SND_CONST) + render/atari/build/sound_dosound.h (SND_DOSOUND), the
shared fixture home the m68k cross builds already -I.

The sound driver reads two kinds of constant from the original program's own data segment (NOT
asset-file content, so they are baked here exactly like gen_game_fixture.py bakes the object /
road / flow tables):

  * SND_CONST — the const tables (pitch / envelope / period / modulation / tune / fx) AND the tune
    note streams the voice stepper walks, laid out as ONE window based at SND_STATE. Every offset the
    driver uses is expressed relative to SND_STATE: an absolute table at Ghidra address A is read at
    SND_CONST[A - SND_STATE], and a per-voice stream/loop cursor is already stored SND_STATE-relative
    in the image, so it indexes SND_CONST directly. The window's low SND_STATE_BYTES also carry the
    driver's power-on state (two nonzero defaults — EG volume and master volume) that rm_sound_reset
    seeds; the running driver never reads const data from there.

  * SND_DOSOUND — the five TOS Dosound command lists (collide / crash / idle / beep / go). These are
    hardware-only (played through the XBIOS Dosound trap on-target, invisible to the differential);
    baked into a SEPARATE header (sound_dosound.h) that only the on-target real-Dosound seam includes.

The window bytes past the program image end (fx record 9 and a small tail) read as bss zeros on the
real 68000, so they are emitted as zeros here — matching what INITFX(9) reads.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REMASTER = HERE.parents[1]
RECREATE = REMASTER.parent / "recreate"
sys.path.insert(0, str(RECREATE.parents[2] / "tools"))   # reverse/tools — the shared recreate kit
from recreate_kit import project                        # noqa: E402
project.load(RECREATE)                                  # binds the kit's loader/emu to recreate
sys.path.insert(0, str(HERE))

from loader import load_image      # noqa: E402
from fixture_lib import emit_header, write_if_changed  # noqa: E402  loader-only shared emit helper (see fixture_lib.py)

PRG = RECREATE.parent / "bin" / "BUGGYBOY.PRG"

# --- the const window (mirror include/sound.h) --------------------------------------------------
SND_STATE = 0x1b05c            # driver state block base; the whole window is offset from here
SND_CONST_END = 0x1bd20        # past fx record 9 (0x1bcf8..0x1bd0a, bss zeros) + a small pad
SND_CONST_BYTES = SND_CONST_END - SND_STATE

# --- the Dosound command lists (mirror include/sound.h SND_DOSOUND_*) ---------------------------
SND_DOSOUND_BASE = 0x18b78     # dosound_collide; the five lists are contiguous from here
SND_DOSOUND_END = 0x18be0


def main():
    img = load_image(PRG)

    const = bytearray(img[SND_STATE:SND_CONST_END])
    const += bytes(SND_CONST_BYTES - len(const))          # zero-pad the tail past the image end
    dosound = bytes(img[SND_DOSOUND_BASE:SND_DOSOUND_END])

    # SND_CONST (the DSP core's tables + tune streams) and SND_DOSOUND (the hardware Dosound lists) go to
    # SEPARATE headers because they have different consumers: src/sound.c reads SND_CONST every frame; the
    # five Dosound lists are hardware-only and only the on-target real-Dosound seam (game_main.c) touches
    # the blob. It is NOT about code size — an unused `static const` array is dropped by GCC, so a merged
    # header would not bloat the .PRG. The wins are (1) no -Wunused-const-variable warning under -Wextra
    # (game_main.c would carry an unused SND_CONST), and (2) explicit per-consumer build dependencies.
    data_out = emit_header("RM_SOUND_DATA_H", [
        "/* Generated by gen_sound_fixture.py — do not edit. The REFRESH sound driver's const tables +",
        " * tune note streams (SND_CONST, based at SND_STATE). See include/sound.h for the offset map;",
        " * the TOS Dosound command lists live in sound_dosound.h. */",
    ], "SND_CONST", const)
    dosound_out = emit_header("RM_SOUND_DOSOUND_H", [
        "/* Generated by gen_sound_fixture.py — do not edit. The five TOS Dosound command lists",
        " * (collide / crash / idle / beep / go), contiguous from SND_DOSOUND_BASE (include/sound.h). The",
        " * on-target real-Dosound seam (render/atari/game_main.c) plays SND_DOSOUND + a SND_DOSOUND_*",
        " * offset through XBIOS Dosound; the host differential logs the offsets instead (a ledger). */",
    ], "SND_DOSOUND", dosound)
    build = HERE / "build"
    build.mkdir(exist_ok=True)
    write_if_changed(build / "sound_data.h", data_out)
    write_if_changed(build / "sound_dosound.h", dosound_out)
    print(f"wrote {build/'sound_data.h'} (SND_CONST {len(const)} bytes @ SND_STATE {SND_STATE:#x}) "
          f"+ {build/'sound_dosound.h'} (SND_DOSOUND {len(dosound)} bytes)")


if __name__ == "__main__":
    main()
