#!/usr/bin/env python3
"""gen_demo_fixture.py — bake the inputs for the interactive road + HUD demo.

The demo renders remaster's own pipeline on a real 68000: each frame it runs rm_build_road_geometry
(from the current pose), rm_render_road, then rm_draw_hud, and blits. Arrow keys nudge the pose
(curve / view bank / near-slope). This bakes, from one captured mid-race frame:

  build/demo_fixture.h  — the HUD asset arrays (shared with the HUD demo) + the render_road static
                          tables (param / edge / edge_const / texture) + the const geometry source
                          tables + the initial pose + the HudState scalars + the palette.
  build/golden.bin      — recreate's g_build_road_geometry + g_render_road + g_draw_hud on a BLANK
                          screen with the SAME pose: the byte-for-byte target for the demo's first
                          frame (before any key), so run_demo.py can prove the on-target pipeline.
  build/palette.bin     — the 16 ST palette words (index 0 black), for the PNG.

Only what remaster's C implements is drawn (road + HUD); there is no captured recreate game frame.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REMASTER = HERE.parents[1]
sys.path.insert(0, str(REMASTER / "test"))

import adapter                                    # noqa: E402
import equiv                                      # noqa: E402
import gen_hud_fixture as hud                      # noqa: E402  reuse the HUD asset/define/palette baking

# A visually busy HUD over the road (same spirit as the HUD demo).
CONTROLS = {adapter.A_flag_seq_count: 3, adapter.A_crash_lap: 4,
            adapter.A_speed: 120, adapter.A_time_left: 45,
            adapter.A_crash_active: 0, adapter.A_hud_crash_timer: 0, adapter.A_dsp_toggle: 0}


def main():
    build = HERE / "build"
    build.mkdir(exist_ok=True)
    sb, nb = adapter.SCREEN_BASE, adapter.SCREEN_BYTES

    # A real mid-race frame: geometry tables built, a plausible pose. Poke the HUD scalars.
    img = equiv.road_background(leg=0, warmup=60)
    for addr, val in CONTROLS.items():
        equiv._w16(img, addr, val & 0xffff)
    img[sb:sb + nb] = bytes(nb)                   # blank screen: draw only remaster's own pipeline

    # golden = recreate's full ported pipeline on the same pose + blank screen (byte-for-byte target).
    ref = bytearray(img)
    equiv._run_pipeline(ref, ("g_build_road_geometry", "g_render_road", "g_draw_hud"))
    (build / "golden.bin").write_bytes(bytes(ref[sb:sb + nb]))

    palette = hud.race_palette(img)
    (build / "palette.bin").write_bytes(palette)

    # ---- render_road static tables + the geometry const sources + the initial pose ----
    buf_b = int.from_bytes(img[adapter.A_buf_b:adapter.A_buf_b + 4], "big")
    edge_sel = adapter._i16(img, adapter.A_road_edge_sel)

    def win(addr, n):
        return bytes(img[addr:addr + n])

    road_arrays = [
        ("fixture_road_param", win(adapter.A_road_param, adapter.ROAD_PARAM_BYTES)),
        ("fixture_road_edge",  win(adapter.A_road_edge_base + edge_sel - adapter.ROAD_EDGE_PAD,
                                   adapter.ROAD_EDGE_WINDOW_BYTES)),
        ("fixture_road_edge_const", win(adapter.A_road_edge_const, adapter.ROAD_CONST_BYTES)),
        ("fixture_road_tex",   win(buf_b - adapter.ROAD_TEX_PAD_LO, adapter.ROAD_TEX_WINDOW_BYTES)),
        ("fixture_road_persp_seg", win(adapter.A_persp_seg_tbl, adapter.ROAD_PERSP_SEG_BYTES)),
        ("fixture_road_width_src", win(adapter.A_road_width_src, adapter.ROAD_WIDTH_SRC_BYTES)),
        ("fixture_road_width_count", win(adapter.A_width_count_tbl, adapter.ROAD_WIDTH_COUNT_BYTES)),
    ]
    pose = adapter.road_pose(img)
    seg = ", ".join(str(pose.seg_data[i]) for i in range(13))

    st = adapter.hud_state(img)
    out = ["/* Generated by gen_demo_fixture.py — do not edit. Inputs for the interactive road + HUD",
           " * demo: HUD assets, render_road static tables, geometry const sources, the initial pose,",
           " * the HudState scalars, and the palette. */",
           "#ifndef RM_DEMO_FIXTURE_H", "#define RM_DEMO_FIXTURE_H", "#include <stdint.h>", ""]
    for name, data in hud.hud_asset_arrays(img):
        out.append(hud._c_array(name, data))
    for name, data in road_arrays:
        out.append(hud._c_array(name, data))
    out.append(hud._c_array("fixture_palette", palette))
    out.append("")
    out += hud.hud_state_defines(st)
    out += ["",
            f"#define ROAD_EDGE_PAD        {adapter.ROAD_EDGE_PAD}",
            f"#define ROAD_TEX_PAD_LO      {adapter.ROAD_TEX_PAD_LO}",
            f"#define ROAD_CURVE_INIT      {pose.curve}",
            f"#define ROAD_VIEW_FLAGS_INIT {pose.view_flags}",
            "#define ROAD_SEG_DATA_INIT   { " + seg + " }",
            "", "#endif /* RM_DEMO_FIXTURE_H */", ""]
    (build / "demo_fixture.h").write_text("\n".join(out))
    print(f"wrote {build/'demo_fixture.h'}, golden.bin, palette.bin "
          f"(curve={pose.curve} view_flags={pose.view_flags} seg0={pose.seg_data[0]} "
          f"buf_b=0x{buf_b:x} edge_sel={edge_sel})")


if __name__ == "__main__":
    main()
