#!/usr/bin/env python3
"""Stage the pre-relocated Joust program image for the on-target build.

The reconstructed cores address the game as ``image + <Ghidra address>``, so every byte of the
original .PRG's text+data has to be present in the shim's BSS image at exactly those offsets — not
because the cores execute any of it, but because they READ it: the object templates, the platform
map, the sprite and font tables, the strings, the sound command lists, and the title picture at
0x23aae. GEMDOS relocates a .PRG for whatever address it loads it at, which is not ours, so the
relocation is done HERE, by the same loader the differential harness uses (recreate_kit's
oracle/loader.py), and joust_main.c reads the result straight into the image.

Extent: ``[load_base, load_base + tlen + dlen)`` — the whole program. Joust has no BSS (blen = 0)
and its data segment ends at 0x2b7ae, so this is every byte a core can reach inside the program.

The result is a build artifact derived from ``../../bin/JOUST.PRG`` (itself untracked); it is
regenerated by build.sh and gitignored.

Usage: gen_image.py <JOUST.PRG> <out/JOUST.IMG>
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3] / "tools"))       # reverse/tools — the shared recreate kit
from recreate_kit import project                         # noqa: E402
project.load(HERE.parent)                                # recreate/ — binds the kit's loader
import loader                                            # noqa: E402


def main():
    prg, out = sys.argv[1], sys.argv[2]
    image = loader.load_image(prg)                       # also sets loader.PROGRAM_END
    lo, hi = loader.LOAD_BASE, loader.PROGRAM_END
    blob = bytes(image[lo:hi])
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_bytes(blob)
    print(f"{out}: {len(blob)} bytes  [{lo:#x},{hi:#x})")


if __name__ == "__main__":
    main()
