#!/usr/bin/env python3
"""Stage the pre-relocated Bubble Ghost program image for the on-target build.

The reconstructed cores address the game as ``image + <Ghidra address>``, so every byte of the
original program has to be present in the shim's BSS image at exactly those offsets — not because
the cores execute any of it, but because they READ it: the 30 KB of graphics inside TEXT, the AES
opcode table at 0x149d2, the sound engine's ISR state block at 0x14932, the file names and format
strings in DATA. GEMDOS relocates a .PRG for whatever address it loads it at, which is not ours, so
the relocation is done HERE, by the same loader the differential harness uses
(``tools/recreate_kit/oracle/loader.py``), and ``bubble_main.c`` reads the result straight into the
image with one GEMDOS Fread.

WHICH .PRG, AND WHY IT IS NOT THE ONE THE HARNESS LOADS. ``../project.toml`` binds the differential
to ``../../bin/GHOST_RT.PRG``, the program in its RUN-TIME layout ``[TEXT][BSS][DATA]``, because the
kit's loader runs no crt0 and this game's crt0 is what rearranges the segments (``../README.md``,
"The image model"). The target build runs the crt0 — ``crt0_relocate_and_clear`` is a verified core
and the machine is where it belongs — so what it needs staged is the FILE layout the crt0 reads:
``GHOST_PLAIN.PRG``, ``[TEXT][DATA]`` with the BSS left to the zeroed array behind it.

That the two agree is not an argument this file makes. ``test/test_image_model.py`` runs the real
crt0 on a file-layout image with a fabricated basepage and asserts the memory it produces equals the
run-time layout the harness loads, byte for byte but one — so the target boot and the harness's base
image are the same bytes by a proof that already exists.

EXTENT: ``[load_base, load_base + tlen + dlen)`` — everything the file carries and nothing else. The
BSS behind it is left to TOS, which zeroes ``.bss``, and to the crt0, which clears it again from the
address the basepage names; the harness's loader leaves it zeroed too, so the two shores agree there
by construction rather than by this file shipping 26 KB of zeros.

The result is a build artifact derived from ``../../bin/GHOST_PLAIN.PRG`` (itself untracked); it is
regenerated by build.sh and gitignored.

Usage: gen_image.py <GHOST_PLAIN.PRG> <disk/GHOST.IMG>
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3] / "tools"))       # reverse/tools — the shared recreate kit
from recreate_kit import project                         # noqa: E402
project.load(HERE.parent)                                # recreate/ — binds the kit's loader
import loader                                            # noqa: E402
import prg_dis                                           # noqa: E402


def main():
    prg, out = sys.argv[1], sys.argv[2]
    image = loader.load_image(prg)                       # also sets loader.PROGRAM_END
    header = prg_dis.parse_header(Path(prg).read_bytes())
    lo = loader.LOAD_BASE
    hi = lo + header["tlen"] + header["dlen"]
    # loader.PROGRAM_END counts the BSS the crt0 will clear; the staged blob deliberately does not.
    # Checking the two against each other is what would catch a .PRG whose header the loader and
    # this file read differently — the blob would then be short, and every global past the cut would
    # be a zero nobody could account for.
    expected_end = hi + header["blen"]
    if expected_end != loader.PROGRAM_END:
        raise SystemExit(f"ERROR: {prg}: the loader ends the program at {loader.PROGRAM_END:#x} and "
                         f"its header's tlen+dlen+blen reaches {expected_end:#x} — the two "
                         f"disagree, so the staged blob would be short or long by that much")
    blob = bytes(image[lo:hi])
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_bytes(blob)
    print(f"{out}: {len(blob)} bytes  [{lo:#x},{hi:#x})  "
          f"bss {header['blen']:#x} left to the crt0, program ends {loader.PROGRAM_END:#x}")


if __name__ == "__main__":
    main()
