#!/usr/bin/env python3
"""mkpak.py - build BLACKICE.PAK from the engine's own asset arrays.

WHY THE PAK IS GENERATED, NOT AUTHORED.  The Atari target loads its art out of
BLACKICE.PAK; the host reference build renders from the arrays compiled into
src/assets_data.c and src/tables.c.  atari/verify.py compares the target's
rendered pixels against the host's, so the two builds must hold BYTE-IDENTICAL
art - and the only way to guarantee that is to derive one from the other rather
than maintain two copies that can drift.  So `atari/dumpassets` (a host program
linked against those very arrays) writes them out, and this script packs those
dumps together with the HUD art, the font and the compiled levels.

WHY THE HUD PALETTE IS ASSERTED, NOT CONVERTED.  The HUD strip is the one asset
still authored by hand, as a palettised PNG whose pixel values are palette
indices.  For those indices to mean anything, the art pass's palette
(art/palette.py) and the engine's (src/tables.c's g_palette_rgb, generated by
tools/mktables.py) have to be the SAME sixteen colours.  This script therefore
matches every index the HUD uses against the engine palette in CIE Lab - per
pipeline/README.md section 9, because on a 16-colour gamut a nearest-RGB search
picks hue-shifted neighbours that are numerically close and visibly wrong - and
requires each one to find ITSELF, at distance zero.

It deliberately does NOT remap a disagreement away.  A remap would silently
paper over a diverged palette, and the divergence is the thing worth knowing:
the two tables are hard-coded independently, and when this check was first run
they disagreed on 11 of the 12 indices the HUD uses, with indices 12/13/14
outright PERMUTED (the art pass's RIM white / ALERT orange / INTEGRITY green
against the engine table's green / white / orange).  The map table is printed on
every run so the identity is visible rather than assumed.

    python3 mkpak.py --dumps <dir> --levels <dir> --hud <png> --out BLACKICE.PAK
"""
from __future__ import annotations

import argparse
import re
import struct
import sys
from pathlib import Path
from typing import NamedTuple

import numpy as np
from PIL import Image

# The packer, the font, the palette encoder and the Lab match are the pipeline's,
# not ours: each of those formats has exactly one implementation and it lives there.
PIPELINE_DIR = Path(__file__).resolve().parent.parent / "pipeline"
sys.path.insert(0, str(PIPELINE_DIR))

from stepix import font                                                     # noqa: E402
from stepix.colourspace import nearest_lab_index, srgb_to_lab               # noqa: E402
from stepix.pack import METHOD_LZSS, METHOD_STORED, build_pak, read_pak, read_pak_directory  # noqa: E402
from stepix.palette import PALETTE_SIZE, ste_word                           # noqa: E402
from stepix.planar import indices_to_planar                                 # noqa: E402

# ---- dump files written by atari/dumpassets ----------------------------------

WALLTEX_DUMP = "walltex.bin"
SPRTEX_DUMP = "sprtex.bin"
PALETTE_DUMP = "palette.bin"

# ---- palette -----------------------------------------------------------------

RGB_CHANNELS = 3
PALETTE_RGB_BYTES = PALETTE_SIZE * RGB_CHANNELS
CHANNEL_TO_INTENSITY_SHIFT = 4      # 8-bit channel -> the STE's 4-bit intensity

# ---- HUD art -----------------------------------------------------------------

HUD_WIDTH = 320
HUD_HEIGHT = 40
#: The title is a whole screen of the same planar format, and it goes through the same palette
#: check for the same reason: it is authored art whose pixel values are indices into the engine's
#: table, and a divergence would repaint it in colours nobody chose.
TITLE_WIDTH = 320
TITLE_HEIGHT = 200
HUD_PNG_MODE = "P"                  # palettised: the pixel VALUES are palette indices

# ---- levels ------------------------------------------------------------------

LEVEL_BLOB_GLOB = "*.bil"
LEVEL_MEMBER_PREFIX = "LEVEL"
LEVEL_MEMBER_MAX = 8                # the engine's level table has eight slots

# levels/ mixes two naming schemes - level1.bil, level2.bil, then level03.bil
# through level08.bil - so a plain filename sort puts level03 first and drops the
# real levels 1 and 2 into slots 7 and 8.  The trailing digits are the level
# number and are what the slot is taken from.  Renaming the first two to
# level01/level02 would make this regex redundant; until then it is load-bearing.
LEVEL_NUMBER_PATTERN = re.compile(r"(\d+)$")

# ---- member names ------------------------------------------------------------

MEMBER_WALLTEX = "WALLTEX"
MEMBER_SPRTEX = "SPRTEX"
MEMBER_PALETTE = "PALETTE"
MEMBER_HUD = "HUD"
MEMBER_TITLE = "TITLE"
MEMBER_FONT = "FONT"

METHOD_NAMES = {METHOD_STORED: "stored", METHOD_LZSS: "lzss"}


def refuse(message: str) -> None:
    """Abort with a diagnostic. Every check in this script is fatal by design."""
    raise SystemExit(f"mkpak: {message}")


def rgb_hex(colour) -> str:
    return "#" + "".join(f"{int(channel):02X}" for channel in colour)


# ---- palette -----------------------------------------------------------------


def read_engine_palette(dumps_dir: Path) -> list[tuple[int, int, int]]:
    """The engine's `g_palette_rgb` as 16 8-bit RGB triples."""
    blob = (dumps_dir / PALETTE_DUMP).read_bytes()
    if len(blob) != PALETTE_RGB_BYTES:
        refuse(f"{PALETTE_DUMP} is {len(blob)} bytes, expected {PALETTE_RGB_BYTES}")
    return [tuple(blob[index * RGB_CHANNELS:(index + 1) * RGB_CHANNELS]) for index in range(PALETTE_SIZE)]


def ste_palette_member(rgb_triples: list[tuple[int, int, int]]) -> bytes:
    """16 big-endian STE colour words - the exact bytes the engine pokes at $ffff8240."""
    words = [ste_word(*(channel >> CHANNEL_TO_INTENSITY_SHIFT for channel in triple)) for triple in rgb_triples]
    return struct.pack(f">{len(words)}H", *words)


# ---- HUD ---------------------------------------------------------------------


class PaletteMapRow(NamedTuple):
    """One HUD index and the engine palette entry it matches. Identity is the contract."""

    png_index: int
    png_rgb: tuple[int, int, int]
    engine_index: int
    engine_rgb: tuple[int, int, int]
    delta_e: float

    @property
    def is_identity(self) -> bool:
        """True when the index found itself and the two triples are the same bytes.

        THE TEST IS ON THE INTEGERS, NOT ON delta_e. The contract is "the same sixteen colours",
        which is an exact comparison of 8-bit triples; the Lab distance exists to name the nearest
        WRONG colour when that fails, and is not itself evidence of anything. Written as
        `delta_e == 0.0` this refused the title screen over index 15 matching itself at a distance
        of 1.07e-14 - a round-trip through Lab and back, not a divergence.
        """
        return self.engine_index == self.png_index and self.engine_rgb == self.png_rgb


def png_colours_of(png_path: Path, image: Image.Image, used_indices: list[int]) -> list[tuple[int, int, int]]:
    """The PNG's own RGB triple for each index the image actually uses."""
    png_palette = image.getpalette() or []
    colours = []
    for index in used_indices:
        start = index * RGB_CHANNELS
        if start + RGB_CHANNELS > len(png_palette):
            refuse(f"{png_path} uses index {index} but its PNG palette defines only "
                   f"{len(png_palette) // RGB_CHANNELS} colours")
        colours.append(tuple(png_palette[start:start + RGB_CHANNELS]))
    return colours


def build_hud_palette_map(png_path: Path, image: Image.Image, used_indices: list[int],
                          engine_rgb: list[tuple[int, int, int]]) -> list[PaletteMapRow]:
    """Nearest engine palette entry, in CIE Lab, for every index the HUD uses.

    Only the used indices are matched: an unused slot in the art tool's palette
    says nothing about the shipped pixels.
    """
    png_rgb = png_colours_of(png_path, image, used_indices)
    engine_lab = srgb_to_lab(np.asarray(engine_rgb, dtype=np.float64))
    source = np.asarray(png_rgb, dtype=np.float64)

    matches = nearest_lab_index(source, engine_lab)
    # The search is the library's; this is only the chosen pair's distance, which
    # is what separates "found itself" from "found the nearest other colour".
    distances = np.linalg.norm(srgb_to_lab(source) - engine_lab[matches], axis=1)

    return [PaletteMapRow(png_index, colour, int(match), engine_rgb[int(match)], float(distance))
            for png_index, colour, match, distance in zip(used_indices, png_rgb, matches, distances)]


def check_hud_palette_map(png_path: Path, rows: list[PaletteMapRow]) -> None:
    """Print the map, then refuse unless every used index matched itself exactly.

    A row can fail two ways and both matter: the index found a DIFFERENT entry
    (the palettes are permuted, so the HUD would draw the wrong colour), or it
    found itself at a non-zero distance (the same slot has been re-toned, so the
    HUD was drawn against shades the engine no longer holds).
    """
    print("HUD palette check (art PNG index -> nearest engine palette entry, CIE Lab)")
    print(f"  {'png':>3} {'png rgb':<9} {'->':^4} {'eng':>3} {'engine rgb':<10} {'dE':>7}  ok")
    for row in rows:
        print(f"  {row.png_index:>3} {rgb_hex(row.png_rgb):<9} {'->':^4} "
              f"{row.engine_index:>3} {rgb_hex(row.engine_rgb):<10} {row.delta_e:>7.2f}  "
              f"{'yes' if row.is_identity else 'NO'}")

    broken = [row for row in rows if not row.is_identity]
    if broken:
        detail = "\n".join(f"  index {row.png_index}: art {rgb_hex(row.png_rgb)} is engine index "
                           f"{row.engine_index} {rgb_hex(row.engine_rgb)}, dE {row.delta_e:.2f}"
                           for row in broken)
        refuse(f"{png_path} and the engine palette are not the same sixteen colours "
               f"({len(broken)} of {len(rows)} used indices differ):\n{detail}\n"
               "art/palette.py and tools/mktables.py hard-code the palette independently and have "
               "diverged; make one import the other and regenerate src/tables.c.")


def planar_screen_member(png_path: Path, size: tuple[int, int],
                         engine_rgb: list[tuple[int, int, int]]) -> bytes:
    """A palettised PNG as ST 4-bitplane word-interleaved bytes, 160 per row.

    Both the HUD strip and the title screen come through here: they are the same format at two
    heights, and they need the same palette check for the same reason.
    """
    image = Image.open(png_path)
    if image.mode != HUD_PNG_MODE:
        refuse(f"{png_path} is mode {image.mode!r}, expected {HUD_PNG_MODE!r} "
               "(its pixel values must be palette indices, not colours)")
    if image.size != size:
        refuse(f"{png_path} is {image.size[0]}x{image.size[1]}, expected {size[0]}x{size[1]}")

    # int32, not uint8: an out-of-range index has to be visible before any cast.
    indices = np.asarray(image, dtype=np.int32)
    used_indices = [int(value) for value in np.unique(indices)]
    if used_indices[-1] >= PALETTE_SIZE:
        refuse(f"{png_path} uses index {used_indices[-1]}, outside the {PALETTE_SIZE}-colour palette")

    check_hud_palette_map(png_path, build_hud_palette_map(png_path, image, used_indices, engine_rgb))
    return indices_to_planar(indices)


# ---- levels ------------------------------------------------------------------


def level_number_of(path: Path) -> int:
    """The level number in a blob's filename - the PAK slot it belongs in."""
    match = LEVEL_NUMBER_PATTERN.search(path.stem)
    if match is None:
        refuse(f"{path.name} has no trailing level number, so its PAK slot is undefined")
    number = int(match.group(1))
    if not 1 <= number <= LEVEL_MEMBER_MAX:
        refuse(f"{path.name} is level {number}, outside the {LEVEL_MEMBER_MAX} slots the PAK has")
    return number


def level_members(levels_dir: Path) -> dict[str, bytes]:
    """The compiled level blobs as LEVEL1..LEVEL8, in game order."""
    paths = sorted(levels_dir.glob(LEVEL_BLOB_GLOB))
    if not paths:
        refuse(f"no {LEVEL_BLOB_GLOB} blobs in {levels_dir}")

    by_number: dict[int, Path] = {}
    for path in paths:
        number = level_number_of(path)
        if number in by_number:
            refuse(f"{path.name} and {by_number[number].name} both claim "
                   f"{LEVEL_MEMBER_PREFIX}{number}")
        by_number[number] = path

    return {f"{LEVEL_MEMBER_PREFIX}{number}": path.read_bytes()
            for number, path in sorted(by_number.items())}


# ---- report and verify --------------------------------------------------------


def print_report(pak_blob: bytes) -> None:
    print(f"{'member':<10}{'raw':>9}{'packed':>9}  {'method':<8}{'ratio':>7}")
    for entry in read_pak_directory(pak_blob):
        method = METHOD_NAMES.get(entry.method, str(entry.method))
        print(f"{entry.name:<10}{entry.raw_len:>9}{entry.packed_len:>9}  {method:<8}{entry.ratio:>7.3f}")
    print(f"total PAK size: {len(pak_blob)} bytes")


def verify_round_trip(pak_blob: bytes, members: dict[str, bytes]) -> None:
    """Read the archive back and assert every member survives byte-for-byte."""
    unpacked = read_pak(pak_blob)
    broken = [name for name, raw in members.items() if unpacked.get(name) != raw]
    if broken or len(unpacked) != len(members):
        raise RuntimeError(f"PAK round-trip failed for {broken or 'an unexpected member set'}")
    print(f"verified {len(members)} members")


# ---- driver -------------------------------------------------------------------


def build_members(dumps_dir: Path, levels_dir: Path, hud_png: Path,
                  title_png: Path) -> dict[str, bytes]:
    engine_rgb = read_engine_palette(dumps_dir)
    members = {
        MEMBER_WALLTEX: (dumps_dir / WALLTEX_DUMP).read_bytes(),
        MEMBER_SPRTEX: (dumps_dir / SPRTEX_DUMP).read_bytes(),
        MEMBER_PALETTE: ste_palette_member(engine_rgb),
        MEMBER_HUD: planar_screen_member(hud_png, (HUD_WIDTH, HUD_HEIGHT), engine_rgb),
        MEMBER_TITLE: planar_screen_member(title_png, (TITLE_WIDTH, TITLE_HEIGHT), engine_rgb),
        MEMBER_FONT: font.font_bytes(),
    }
    members.update(level_members(levels_dir))
    return members


def main() -> None:
    parser = argparse.ArgumentParser(description="Pack BLACKICE.PAK from the engine's own asset arrays.")
    parser.add_argument("--dumps", required=True, type=Path, help="directory written by atari/dumpassets")
    parser.add_argument("--levels", required=True, type=Path, help="directory of compiled .bil level blobs")
    parser.add_argument("--hud", required=True, type=Path, help="320x40 palettised HUD strip PNG")
    parser.add_argument("--title", required=True, type=Path,
                        help="320x200 palettised title screen PNG")
    parser.add_argument("--out", required=True, type=Path, help="the .PAK to write")
    args = parser.parse_args()

    members = build_members(args.dumps, args.levels, args.hud, args.title)
    pak_blob = build_pak(members)
    args.out.write_bytes(pak_blob)

    print_report(pak_blob)
    verify_round_trip(pak_blob, members)


if __name__ == "__main__":
    main()
