#!/usr/bin/env python3
"""Compile an input script into bench_script.h — one input word per simulation tick.

WHY THE SCRIPT IS COMPILED IN. atari/verify.py's whole claim is that the target and the host
reference drew the same frame, and that only holds if they were fed the same input. The host takes
its script as a file (host/main_host.c's --script); the target cannot, because reading one would
put a GEMDOS call and a parser between the measurement and the thing measured, and because the
bench must run with no input hardware attached at all. So the SAME text file becomes a C array
here, and the two builds share one source of truth for the run.

The token names and their bit values are include/player.h's INPUT_*; this script parses them out
of that header rather than restating them, so a new input bit cannot silently mean nothing here.

    mkscript.py <player.h> <script.txt> <bench_script.h>
"""
import re
import sys

#: Script token -> the include/player.h macro it means. This is host/main_host.c's INPUT_TOKENS
#: table; the two read the same scripts, so they name the same things. A token whose macro the
#: header no longer defines is an error only when a script actually uses it — the input bits are
#: being reworked alongside this build, and a reserved bit nobody names must not fail the build.
TOKENS = {
    "forward": "INPUT_FORWARD",
    "back": "INPUT_BACK",
    "turn_left": "INPUT_TURN_LEFT",
    "turn_right": "INPUT_TURN_RIGHT",
    "strafe_left": "INPUT_STRAFE_LEFT",
    "strafe_right": "INPUT_STRAFE_RIGHT",
    "fire": "INPUT_FIRE",
    "throttle": "INPUT_THROTTLE_NEXT",
}
NO_INPUT = "-"
COMMENT = "#"
VALUES_PER_LINE = 12
HEADER_GUARD = "BLACKICE_BENCH_SCRIPT_H"


def input_bits(player_h):
    """The INPUT_* bit values as include/player.h defines them, keyed by script token."""
    text = open(player_h).read()
    found = dict(re.findall(r"^#define\s+(INPUT_\w+)\s+(0x[0-9a-fA-F]+)", text, re.M))
    return {token: int(found[name], 0) for token, name in TOKENS.items() if name in found}


def compile_script(path, bits):
    """One entry per tick. A line is `<ticks> <token>...`, and '-' means no input at all."""
    ticks = []
    for number, line in enumerate(open(path).read().splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith(COMMENT):
            continue
        words = stripped.split()
        try:
            repeat = int(words[0])
        except ValueError:
            raise SystemExit(f"REFUSED: {path}:{number} does not start with a tick count")
        # host/main_host.c's loader refuses a non-positive repeat and test/test_replay.py pins that;
        # a script this accepts and the host rejects would have the two replaying different runs,
        # which is the one thing the compiled-in copy exists to prevent.
        if repeat <= 0:
            raise SystemExit(f"REFUSED: {path}:{number} has a tick count of {repeat}")
        value = 0
        for word in words[1:]:
            if word == NO_INPUT:
                continue
            if word not in bits:
                raise SystemExit(f"REFUSED: {path}:{number} names an unknown input '{word}'")
            value |= bits[word]
        ticks.extend([value] * repeat)
    if not ticks:
        raise SystemExit(f"REFUSED: {path} compiles to no ticks")
    return ticks


def emit(path, source, ticks):
    lines = [
        "/* bench_script.h — GENERATED by mkscript.py. Do not edit; edit the input script. */",
        f"/* Compiled from {source}: {len(ticks)} ticks, one input word each. */",
        f"#ifndef {HEADER_GUARD}",
        f"#define {HEADER_GUARD}",
        "",
        f"#define BENCH_SCRIPT_TICKS {len(ticks)}",
        "",
        "static const unsigned short BENCH_SCRIPT[BENCH_SCRIPT_TICKS] = {",
    ]
    for start in range(0, len(ticks), VALUES_PER_LINE):
        row = ticks[start:start + VALUES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{value:04x}" for value in row) + ",")
    lines += ["};", "", f"#endif /* {HEADER_GUARD} */", ""]
    open(path, "w").write("\n".join(lines))


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__.strip().splitlines()[-1].strip())
    player_h, script, out = sys.argv[1:4]
    ticks = compile_script(script, input_bits(player_h))
    emit(out, script, ticks)
    print(f"{out}: {len(ticks)} ticks from {script}")


if __name__ == "__main__":
    main()
