/* blackice_sfx_ids.h — GENERATED by songs/blackice.py; edit that, not this.
 *
 * DESIGN.md §16's cue table. Index N is the same event on both paths: blackice_sfx.py packs the
 * DMA samples in this order and blackice.py's SFX_MACROS lists the YM stand-ins in it. */
#ifndef BLACKICE_SFX_IDS_H
#define BLACKICE_SFX_IDS_H

#define BLACKICE_SFX_COUNT 10

#define SFX_BUSTER_SHOT      0
#define SFX_SPIKE_SHOT       1
#define SFX_WATCHDOG_SNARL   2
#define SFX_SENTRY_CHARGE    3
#define SFX_GATE_OPEN        4
#define SFX_TOKEN_GRAB       5
#define SFX_TRACE_ALARM      6
#define SFX_PLAYER_HIT       7
#define SFX_ENEMY_DISSOLVE   8
#define SFX_EXFIL_SIREN      9

/* Indexed by the ids above. A request of HIGHER OR EQUAL priority preempts the playing one; a
 * strictly lower one is dropped, never queued (DESIGN.md §16). */
static const unsigned char blackice_sfx_priority[BLACKICE_SFX_COUNT] = { 1, 2, 1, 2, 2, 2, 3, 3, 2, 3 };

#endif /* BLACKICE_SFX_IDS_H */
