/* blackice_song.h — GENERATED by songs/blackice.py; edit that, not this.
 *
 * The BLACK ICE score, 5004 bytes of song data in five blobs:
 *   blackice_title     790 B    30.7 s at speed 12
 *   blackice_score    2946 B   197.1 s at speed 11
 *   blackice_death     306 B     2.9 s at speed 6
 *   blackice_clear     354 B     3.8 s at speed 6
 *   blackice_exfil     608 B     2.2 s at speed 7
 *
 * blackice_score is played at FOUR tempi, one per trace band; the game switches with
 * ym_music_set_speed(BLACKICE_BAND_SPEED[band]) and the loop plays on from where it was:
 *   band 0  speed 11  136.4 BPM
 *   band 1  speed 10  150.0 BPM
 *   band 2  speed  9  166.7 BPM
 *   band 3  speed  8  187.5 BPM
 */
#ifndef BLACKICE_SONG_H
#define BLACKICE_SONG_H

#define BLACKICE_BAND_COUNT 4

/* The smallest frames-per-row any band is played at — so the fastest the drum lane can ever step,
 * and therefore the most hits a window of N frames can hold. A compile-time constant because the
 * harness sizes its drum ledger against it, and BLACKICE_BAND_SPEED[] is an array. */
#define BLACKICE_FASTEST_BAND_SPEED 8

/* Frames per row at 50 Hz, indexed by trace band (0 = 0-25%, 3 = 75-100%). */
static const unsigned short BLACKICE_BAND_SPEED[BLACKICE_BAND_COUNT] = { 11, 10, 9, 8 };

#define BLACKICE_TITLE_BYTES 790
extern const unsigned char blackice_title[BLACKICE_TITLE_BYTES];

#define BLACKICE_SCORE_BYTES 2946
extern const unsigned char blackice_score[BLACKICE_SCORE_BYTES];

#define BLACKICE_DEATH_BYTES 306
extern const unsigned char blackice_death[BLACKICE_DEATH_BYTES];

#define BLACKICE_CLEAR_BYTES 354
extern const unsigned char blackice_clear[BLACKICE_CLEAR_BYTES];

#define BLACKICE_EXFIL_BYTES 608
extern const unsigned char blackice_exfil[BLACKICE_EXFIL_BYTES];

#endif /* BLACKICE_SONG_H */
