/* blackice_sfx_bank.h — GENERATED by songs/blackice_sfx.py; edit that, not this.
 *
 * 10 samples, 8-bit signed mono at 12517 Hz, 60176 bytes:
 *   0  buster_shot        1252 B  0.10 s  priority 1
 *   1  spike_shot         4382 B  0.35 s  priority 2
 *   2  watchdog_snarl     3756 B  0.30 s  priority 1
 *   3  sentry_charge      5634 B  0.45 s  priority 2
 *   4  gate_open          6884 B  0.55 s  priority 2
 *   5  token_grab         3130 B  0.25 s  priority 2
 *   6  trace_alarm       11266 B  0.90 s  priority 3
 *   7  player_hit         3756 B  0.30 s  priority 3
 *   8  enemy_dissolve     5008 B  0.40 s  priority 2
 *   9  exfil_siren       15020 B  1.20 s  priority 3
 */
#ifndef BLACKICE_SFX_BANK_H
#define BLACKICE_SFX_BANK_H

#define BLACKICE_SFX_BANK_BYTES 60176
#define BLACKICE_SFX_BANK_COUNT 10

extern const unsigned char blackice_sfx_bank[BLACKICE_SFX_BANK_BYTES];

#endif /* BLACKICE_SFX_BANK_H */
