/* sfx_bank.h — GENERATED by mk_samples.py; edit that, not this.
 *
 * 6 samples, 8-bit signed mono at 12517 Hz, 36110 bytes:
 *   0  gunshot        4006 B  0.32 s
 *   1  door          11266 B  0.90 s
 *   2  pickup         3756 B  0.30 s
 *   3  enemy_hit      2004 B  0.16 s
 *   4  player_hurt    5634 B  0.45 s
 *   5  enemy_death    9388 B  0.75 s
 */
#ifndef SFX_BANK_H
#define SFX_BANK_H

#define SFX_BANK_BYTES 36110
#define SFX_BANK_COUNT 6

extern const unsigned char sfx_bank[SFX_BANK_BYTES];

#endif /* SFX_BANK_H */
