/* sfx_ids.h — GENERATED by mk_song.py; edit the description there, not this. */
#ifndef SFX_IDS_H
#define SFX_IDS_H

#define SFX_COUNT 6

#define SFX_GUNSHOT        0
#define SFX_DOOR           1
#define SFX_PICKUP         2
#define SFX_ENEMY_HIT      3
#define SFX_PLAYER_HURT    4
#define SFX_ENEMY_DEATH    5

/* Indexed by the ids above. Higher wins: a request is refused only by a STRICTLY higher one that
 * is still sounding. */
static const unsigned char sfx_priority[SFX_COUNT] = { 6, 2, 3, 4, 5, 5 };

#endif /* SFX_IDS_H */
