/* song_data.h — GENERATED by mk_song.py; edit the description there, not this. */
#ifndef SONG_DATA_H
#define SONG_DATA_H

#define DEMO_SONG_BYTES 1892

extern const unsigned char demo_song[DEMO_SONG_BYTES];

#endif /* SONG_DATA_H */
