/* ym_notes.h — GENERATED by mk_song.py; edit that, not this.
 *
 * The YM tone period for each semitone index, index 0 = C-1 at
 * 32.703 Hz. period = 2000000 / (16 * frequency), rounded.
 *
 * NOTHING IN THIS TABLE IS CLAMPED. The tone counter is 12 bits — 1 to 4095 — and these
 * 96 notes span 3822 down to 16, clear of both ends, which is how the
 * note range was chosen: every entry is the pitch it says it is, with no flat spot at the bottom
 * where the counter would have run out. (mk_song.py's note_period() does clamp, and that is what
 * would catch a NOTE_COUNT or a base frequency edited past what the hardware can play.)
 */
#ifndef YM_NOTES_H
#define YM_NOTES_H

#include <stdint.h>

static const uint16_t ym_note_period[96] = {
     3822,  3608,  3405,  3214,  3034,  2863,  2703,  2551,  2408,  2273,  2145,  2025,   /* C-1 .. B-1 */
     1911,  1804,  1703,  1607,  1517,  1432,  1351,  1276,  1204,  1136,  1073,  1012,   /* C-2 .. B-2 */
      956,   902,   851,   804,   758,   716,   676,   638,   602,   568,   536,   506,   /* C-3 .. B-3 */
      478,   451,   426,   402,   379,   358,   338,   319,   301,   284,   268,   253,   /* C-4 .. B-4 */
      239,   225,   213,   201,   190,   179,   169,   159,   150,   142,   134,   127,   /* C-5 .. B-5 */
      119,   113,   106,   100,    95,    89,    84,    80,    75,    71,    67,    63,   /* C-6 .. B-6 */
       60,    56,    53,    50,    47,    45,    42,    40,    38,    36,    34,    32,   /* C-7 .. B-7 */
       30,    28,    27,    25,    24,    22,    21,    20,    19,    18,    17,    16,   /* C-8 .. B-8 */
};

#endif /* YM_NOTES_H */
