#!/usr/bin/env python3
"""Stage the pre-relocated Flying Shark program image for the on-target build.

    python3 atari/gen_image.py ../bin/FLYSHARK.PRG atari/disk/FLYSHARK.IMG

The reconstructed cores address the game as ``image + <Ghidra address>``, so every byte of the
original .PRG's TEXT and DATA has to be present in the shim's array at exactly those offsets — not
because the cores execute any of it, but because they READ it: the file records the loader walks,
the level table, the sprite and enemy descriptors, the text scripts, the hall of fame, the colour
tables and the map header. GEMDOS relocates a .PRG for whatever address it loads it at, which is not
ours, so the relocation is done HERE by the same loader the differential harness uses
(``recreate_kit``'s ``oracle/loader.py``), and ``flyshark_main.c`` reads the result straight into the
image at ``FS_LOAD_BASE``.

EXTENT: ``[load_base, load_base + tlen + dlen)`` — TEXT and DATA and no more. The .PRG's 0x3f0a8
bytes of BSS are not in the file and are not staged: TOS zeroes the shim's array exactly as the
harness's ``calloc`` zeroes the oracle's, and the eight files the boot chain loads off disc A are
what fill it. Staging zeroes instead would put 306 KB on a 720 KB floppy for nothing.

The result is a build artifact derived from ``../bin/FLYSHARK.PRG`` (itself untracked); it is
regenerated by build.sh and gitignored.
"""
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3] / "tools"))       # reverse/tools — the shared recreate kit
from recreate_kit import project                         # noqa: E402
project.load(HERE.parent)                                # recreate/ — binds the kit's loader
import loader                                            # noqa: E402

# The GEMDOS header's first three longwords after the magic: text, data and bss lengths. Read here
# rather than taken from a constant so that a rebuilt .PRG cannot disagree with this file.
PRG_HEADER = ">HIII"
PRG_MAGIC = 0x601A


def segment_bytes(prg_path):
    """TEXT + DATA of a GEMDOS .PRG — what a loader copies out of the file."""
    magic, tlen, dlen, _blen = struct.unpack_from(PRG_HEADER, Path(prg_path).read_bytes())
    if magic != PRG_MAGIC:
        raise SystemExit(f"{prg_path}: not a GEMDOS .PRG (magic {magic:#06x})")
    return tlen + dlen


def main():
    prg, out = sys.argv[1], Path(sys.argv[2])
    image = loader.load_image(prg)                        # also sets loader.PROGRAM_END
    lo = loader.LOAD_BASE
    hi = lo + segment_bytes(prg)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(bytes(image[lo:hi]))
    print(f"{out}: {hi - lo} bytes  [{lo:#x},{hi:#x})  "
          f"bss {loader.PROGRAM_END - hi} bytes zeroed by TOS")


if __name__ == "__main__":
    main()
